In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import os
import kagglehub


In [5]:
path = kagglehub.dataset_download("saurabh00007/iriscsv")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\buvan\.cache\kagglehub\datasets\saurabh00007\iriscsv\versions\1


In [6]:
file_name = "Iris.csv"
df = pd.read_csv(os.path.join(path,file_name))

In [7]:
df.head

<bound method NDFrame.head of       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0      1            5.1           3.5            1.4           0.2     Iris-setosa
1      2            4.9           3.0            1.4           0.2     Iris-setosa
2      3            4.7           3.2            1.3           0.2     Iris-setosa
3      4            4.6           3.1            1.5           0.2     Iris-setosa
4      5            5.0           3.6            1.4           0.2     Iris-setosa
..   ...            ...           ...            ...           ...             ...
145  146            6.7           3.0            5.2           2.3  Iris-virginica
146  147            6.3           2.5            5.0           1.9  Iris-virginica
147  148            6.5           3.0            5.2           2.0  Iris-virginica
148  149            6.2           3.4            5.4           2.3  Iris-virginica
149  150            5.9           3.0            5.1     

In [8]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [9]:
print(df.columns)

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')


In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
df = df.drop(columns=['Id'])
# Features & Target
X = df.drop(columns=['Species'])
y = df['Species']
le=LabelEncoder()
y = le.fit_transform(y)

In [12]:
#Train and test
# we use scikit learn -> model selection -> Train and test spilt

from sklearn.model_selection import train_test_split


In [13]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [14]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

,criterion,'gini'
,splitter,'best'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,None
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,class_weight,None


In [15]:
y_pred = model.predict(X_test)

In [16]:
print(y_pred)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]


In [17]:
print(y_test)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]


In [18]:
import pandas as pd

user_input = pd.DataFrame(
    [[5.1, 3.5, 1.4, 0.2]],
    columns=X.columns
)

prediction = model.predict(user_input)

print(le.inverse_transform(prediction))

['Iris-setosa']


In [20]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [21]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_pred)
print(accuracy)

1.0


In [26]:
from sklearn.metrics import f1_score
f1=f1_score(y_test,y_pred,average='macro')
print(f1)

1.0


In [23]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



# Loan Approval

In [28]:
import pandas as pd

# Create dataset
data = {
    'Age': [25, 40, 35, 28, 50],
    'Income': [30000, 60000, 45000, 35000, 80000],
    'CreditScore': [650, 700, 680, 620, 750],
    'LoanAmount': [10000, 20000, 15000, 12000, 25000],
    'Approved': ['No', 'Yes', 'Yes', 'No', 'Yes']
}
df = pd.DataFrame(data)
print(df)

   Age  Income  CreditScore  LoanAmount Approved
0   25   30000          650       10000       No
1   40   60000          700       20000      Yes
2   35   45000          680       15000      Yes
3   28   35000          620       12000       No
4   50   80000          750       25000      Yes


In [29]:
df.isnull().sum()

Age            0
Income         0
CreditScore    0
LoanAmount     0
Approved       0
dtype: int64

In [30]:
from sklearn.model_selection import train_test_split

In [35]:
X = df.drop(columns=['Approved'])
y = df['Approved']

In [40]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [41]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [42]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X_train,y_train)

,criterion,'gini'
,splitter,'best'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,None
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,class_weight,None


In [44]:
y_pred=model.predict(X_test)
print(y_pred)

[1]


In [45]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[1]]


D:\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:534: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(


In [46]:
from sklearn.metrics import classification_report
cr = classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

           1       1.00      1.00      1.00         1

    accuracy                           1.00         1
   macro avg       1.00      1.00      1.00         1
weighted avg       1.00      1.00      1.00         1



In [54]:
import pandas as pd

user_input = pd.DataFrame(
    [[30, 50000, 700, 150000]],
    columns=X.columns
)

prediction = model.predict(user_input)
print(le.inverse_transform(prediction))

result = le.inverse_transform(prediction)[0]

if prediction[0]==1:
    print("Yes")
else:
    print("No")

[1]
Yes
